# Generated by Django 3.2 on 2023-05-10 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Folio')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('published', models.BooleanField(default=False, verbose_name='is it published?')),
            ],
        ),
    ]
